import json,hashlib
from pathlib import Path
P=Path(__file__).resolve().parents[2];O=P/'Documentation/Phase4A';E=Path(r'D:/Epic Games/UE_5.8/Engine')
def evidence(path,terms):
    p=E/path;lines=p.read_text(encoding='utf-8-sig').splitlines()
    return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'matches':[{'line':i+1,'text':line.strip()} for i,line in enumerate(lines) if any(t in line for t in terms)]}
def entry(name,description,exposure,status,sources):return {'name':name,'scope':description,'exposure':exposure,'status':status,'source_evidence':[evidence(p,t) for p,t in sources]}
rig=[
entry('USkeletonModifier','Author/add/remove/parent/mirror/orient explicitly supplied bone transforms. No humanoid fitting.',['C++','Blueprint','Python subset'],'Public authoring API; skeletal editing requires editor; SetDynamicMesh/CommitSkeletonToDynamicMesh C++ only',[('Plugins/Runtime/MeshModelingToolset/Source/SkeletalMeshModifiers/Public/SkeletonModifier.h',['UFUNCTION','AddBone(','SetSkeletalMesh(','SetDynamicMesh(','CommitSkeletonTo','SetBonesTransforms','OrientBone('])]),
entry('FSkeletonViaSampling::ComputeSkeleton','Actual automatic mesh medial sphere sampling; convert tree to animation skeleton; generic geometry branches, not labelled humanoid joints.',['C++'],'Public GeometryAlgorithms headers; low-level algorithm; no direct Python method found',[('Plugins/Runtime/GeometryProcessing/Source/GeometryAlgorithms/Public/Skeletonization/MeshMedialAxisSampling.h',['FSkeletonViaSampling','ComputeSkeleton','ToHierarchy','FMedialSkeletonToTreeSkeletonOptions','MaxSpheres'])]),
entry('Geometry Collection medial Dataflow nodes','MeshMedialSkeletonSampling_v2 -> ConvertMedialSkeletonToAnimationSkeleton_v2 / SkinMeshViaMedialSkeleton_v2. Wrapper tests underlying native algorithms; graph itself not executed.',['Dataflow node registration','C++','Python graph construction/evaluation exposed'],'GeometryCollectionPlugin IsBetaVersion=true, disabled by default; conversion declarations in Private/Dataflow; latest v2 DataflowMesh, legacy DynamicMesh nodes deprecated5.8',[('Plugins/Experimental/GeometryCollectionPlugin/Source/GeometryCollectionNodes/Public/Dataflow/GeometryCollectionSamplingNodes.h',['MedialSkeleton','Deprecated','MeshMedial']),('Plugins/Experimental/GeometryCollectionPlugin/Source/GeometryCollectionNodes/Private/Dataflow/MeshMedialSkeletonConversionNodes.h',['MedialSkeleton','BindSkeleton','UE_DEPRECATED']),('Plugins/Experimental/GeometryCollectionPlugin/GeometryCollectionPlugin.uplugin',['IsBetaVersion','EnabledByDefault','Type'])]),
entry('Static mesh skeletal conversion factory','Create root-only skeleton, or use provided existing skeleton; conversion is not automatic anatomical fitting.',['C++ internal factories','Python classes discoverable but static input property not writable'],'Private Hidden factories; UI conversion utility',[('Plugins/Animation/SkeletalMeshModelingTools/Source/SkeletalMeshModelingTools/Private/SkeletalMeshModelingToolsMeshConverter.h',['UCLASS','Factory','StaticMesh']),('Plugins/Animation/SkeletalMeshModelingTools/Source/SkeletalMeshModelingTools/Private/SkeletalMeshModelingToolsMeshConverter.cpp',['FMeshBoneInfo','RootBone','root','FactoryCreateNew'])]),
entry('GeometryScript_NewAssetUtils','Create persistent Skeletal Mesh from DynamicMesh + existing Skeleton + weights; options use_mesh_bone_proportions and original vertex order.',['C++','Blueprint','Python'],'Public GeometryScriptingEditor asset creation; editor-only',[('Plugins/Runtime/GeometryScripting/Source/GeometryScriptingEditor/Public/GeometryScript/CreateNewAssetUtilityFunctions.h',['CreateNewSkeletalMesh','bUseMeshBoneProportions','bUseOriginalVertexOrder','InSkeleton'])]),
entry('Control Rig / IKRigController automatic characterisation','Existing skeleton control rigs/semantic chain identification/FBIK generation; not unrigged mesh joint discovery.',['C++','Blueprint','Python controller APIs'],'Characterisation fails on all four medial trees, succeeds on both assisted semantic hierarchies',[('Plugins/Animation/IKRig/Source/IKRigEditor/Public/RigEditor/IKRigController.h',['ApplyAuto','SetRetargetRoot','SetRootMotionBone'])])]
skin=[
entry('GeometryScript_BoneWeights.compute_smooth_bone_weights -> FSkinBindingOp','Automatic weights for an existing Skeleton; DirectDistance or GeodesicVoxel. Voxel128, stiffness0.2, max5 tested.',['C++','Blueprint','Python'],'Public API; core implementation with modelling operator; requires supplied skeleton',[('Plugins/Runtime/GeometryScripting/Source/GeometryScriptingCore/Public/GeometryScript/MeshBoneWeightFunctions.h',['ComputeSmoothBoneWeights','GeodesicVoxel','DirectDistance','Stiffness','MaxInfluences','VoxelResolution']),('Plugins/Runtime/GeometryScripting/Source/GeometryScriptingCore/Private/MeshBoneWeightFunctions.cpp',['ComputeSmoothBoneWeights','FSkinBindingOp','SetTransformHierarchyFromReferenceSkeleton']),('Plugins/Runtime/MeshModelingToolset/Source/ModelingOperators/Public/SkinningOps/SkinBindingOp.h',['FSkinBindingOp','BindType','VoxelResolution'])]),
entry('SkinBinding::CreateSkinWeightsFromMedialSkeleton','Engine-native automatic medial skeleton conversion and cluster-constrained skin generation. DirectDistance/max5 tested through thin wrapper.',['C++'],'Public DynamicMesh API; run without imported bone transforms or weights',[('Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/MedialSkeletonSkinBinding.h',['CreateSkinWeightsFromMedialSkeleton','FBindMedialSkeletonSettings','BindSettings'])]),
entry('GeometryScript_BoneWeights.transfer_bone_weights_from_mesh','Transfer donor weights via closest-surface or inpainting; requires donor skeleton/weights, not joint placement. Not used for this proof.',['C++','Blueprint','Python'],'Public API; optional route for future already-rigged input',[('Plugins/Runtime/GeometryScripting/Source/GeometryScriptingCore/Public/GeometryScript/MeshBoneWeightFunctions.h',['TransferBoneWeightsFromMesh','InpaintWeights','ClosestPoint','SourceMesh'])]),
entry('Skeletal Mesh Editing Tools','UI skeleton authoring, binding and weight editing; automation uses corresponding API, not fictitious Auto Rig button.',['Editor UI','C++ operators'],'SkeletalMeshModelingTools plugin no beta/experimental flag; Editor module enabled by default',[('Plugins/Animation/SkeletalMeshModelingTools/SkeletalMeshModelingTools.uplugin',['FriendlyName','EnabledByDefault','Type','IsBeta','IsExperimental'])])]
for name,data in [('autorig_api_inventory.json',rig),('autoskin_api_inventory.json',skin)]:
    (O/name).write_text(json.dumps({'engine_version':json.loads((O/'python_api_probe.json').read_text())['engine_version'],'systems':data,'not_rigging_solutions':['ML Deformer and Mesh Deformer are deformation infrastructure, not a verified mesh-to-humanoid-joint fitter.','No verified heat-binding callable was used; do not advertise an untested binding algorithm.','MetaHuman custom mesh solving/topology replacement excluded by scope.'],'python_evidence':['python_api_probe.json','additional_python_apis.json']},indent=2))
print('API_INVENTORIES_DONE')

