import json,hashlib,subprocess
from pathlib import Path
P=Path(__file__).resolve().parents[2];E=Path('D:/Epic Games/UE_5.8/Engine');O=P/'Documentation/Phase4B';W=P/'Working/Phase4B'
systems=[]
def add(name,patterns,exposure,inputs,outputs,anatomy,topology,changes,reuse,classification,terms):
    source=[];descriptors={}
    for pat in patterns:
        for path in E.glob(pat):
            text=path.read_text(encoding='utf-8-sig',errors='replace');lines=text.splitlines();matches=[]
            for i,line in enumerate(lines):
                if any(t.lower() in line.lower() for t in terms):matches.append({'line':i+1,'excerpt':lines[max(0,i-2):min(len(lines),i+4)]})
            source.append({'path':str(path),'exists':True,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'matches':matches[:45]})
            parent=path.parent
            while parent!=E and parent!=parent.parent:
                ds=list(parent.glob('*.uplugin'))
                if ds:
                    for d in ds:descriptors[str(d)]=json.loads(d.read_text(encoding='utf-8-sig'))
                    break
                parent=parent.parent
    systems.append({'name':name,'installed':bool(source),'source':source,'plugin_descriptors':descriptors,'public_private_editor_runtime':exposure,'cpp_blueprint_python':exposure,'expected_input':inputs,'produced_output':outputs,'infers_anatomy_from_arbitrary_geometry':anatomy,'requires_known_topology':topology,'changes_topology':changes,'reuse_without_converting_lara_to_metahuman':reuse,'authoring_plugin_callability':('Public exported editor C++/reflected boundary subject to listed prerequisites' if 'Public' in exposure else 'Internal/private code is not a supported standalone authoring-plugin API; do not promise binary linkage'),'licensing':'Installed engine code use is subject to the user’s Epic licence; technical exposure is not legal permission. Standard Engine EULA permits development under its conditions; redistribution of editor tools/code/models requires its distribution terms. No model/source redistributed here.','classification':classification})
add('MetaHuman From Custom Mesh / ConformToTargetMeshes',['Plugins/MetaHuman/MetaHumanCharacter/Source/MetaHumanCharacterEditor/Public/MetaHumanCharacterEditorSubsystem.h','Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanCoreTechLib/Private/MetaHumanCharacterBodyIdentity.cpp'],'Public exported Editor C++; reflected subsystem Blueprint/Python when plugin loaded; absent from current editor reflection','Registered MetaHuman Character, arbitrary human target vertices/triangles, optional correspondences and face data','Fitted MetaHuman model/state geometry and joints','Fits semantic model to arbitrary target, not a generic Lara joint-only contract',False,'Output uses MetaHuman topology','Potential temporary donor joint extraction is an untested alternative; full conversion violates retained Lara topology goal','Complete MetaHuman fitting solution; not verified topology-preserving skeleton inference',['ConformTarget','PipelineFitToArbitraryTarget','VolumetricallyFit','ConformToTargetMeshes'])
add('MetaHuman BodyJointEstimator / volumetric hands and feet',['Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanCoreTechLib/Private/bodyshapeeditor/include/bodyshapeeditor/BodyJointEstimator.h','Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanCoreTechLib/Private/bodyshapeeditor/src/BodyJointEstimator.cpp','Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanCoreTechLib/Private/bodyshapeeditor/src/BodyShapeEditor.cpp'],'Private internal C++, no direct Blueprint/Python','Model-specific vertex/joint correspondence matrices and model-state vertices','Joint translations and corrected orientations',False,True,False,'Cannot multiply Lara vertices by MetaHuman correspondence matrices','Useful algorithm evidence, unsuitable direct input',['jvR','vertex_count','vertices *','VolumetricallyFitHand','translationEstimates'])
add('Body Identity template landmarks and models',['Plugins/MetaHuman/MetaHumanCharacter/Content/Body/IdentityTemplate/region_landmarks.json','Plugins/MetaHuman/MetaHumanCharacter/Content/Body/IdentityTemplate/pipeline_presets.json','Plugins/MetaHuman/MetaHumanCharacter/Content/Body/IdentityTemplate/body_joint_mapping.json'],'Plugin Content resources, not inference API','Known combined model vertex IDs/DNA/skin/RBF resources','Region associations, pipeline settings and joint mappings',False,True,False,False,'Useful evidence; not Lara landmarks',['vID','mesh','joint','keypoint','icp'])
add('MetaHuman Identity / face conformer',['Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanCoreTechLib/Public/MetaHumanConformer.h','Plugins/MetaHuman/MetaHumanAnimator/Source/MetaHumanIdentity/Public/MetaHumanIdentityParts.h'],'Public exported Editor C++; reflected Identity subset','Face scan/cameras/landmarks and Identity model','Face identity/head fit','Face only, not body',False,'MetaHuman face output',False,'Irrelevant to whole-body inference',['Fit','Landmark','Conform'])
add('Face/Head ML tracker models',['Plugins/MetaHuman/MetaHumanCharacter/Source/MetaHumanCharacterEditor/Private/MetaHumanCharacterEditorLandmarkTracker.h','Plugins/MetaHuman/MetaHumanCoreTechLib/Source/MetaHumanPipelineCore/Private/Nodes/HyprsenseRealtimeNode.cpp'],'Private Editor tracker; pipeline native C++; NNE runtime interfaces','Rendered/captured face image and model','Facial contours/head pose',False,False,False,'Facial assistance only','No bundled generic 3D humanoid body-joint model verified',['TrackImage','FaceContour','head pose estimation','HeadposeModelVariant'])
add('MeshPlanarSymmetry',['Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Parameterization/MeshPlanarSymmetry.h','Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Private/Parameterization/MeshPlanarSymmetry.cpp'],'Public exported runtime C++ DynamicMesh, no direct reflected Python entry verified','DynamicMesh, bounds, optional candidate plane normals','Symmetry plane and vertex pairs',False,False,False,True,'Useful building block',['FindPlaneAndInitialize','Initialize(','Mirror'])
add('Mesh Wrap / landmark Dataflow',['Plugins/Experimental/MeshResizing/Source/MeshResizingNodes/Public/MeshResizing/MeshWrapNode.h','Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/WrapMesh.h'],'Public C++ geometry API; Experimental Dataflow node structs; no high-level Python human fitter','Source topology, target shape, supplied vertex landmarks','Wrapped source mesh, matched supplied landmarks',False,False,'Keeps source topology, moves its surface','Requires donor and landmark correspondences; not used','Useful geometry fitting, does not discover anatomical landmarks',['Correspondence','Landmark','WrapToTarget'])
add('Medial skeleton / Dataflow sampling',['Plugins/Runtime/GeometryProcessing/Source/GeometryAlgorithms/Public/Skeletonization/MeshMedialAxisSampling.h','Plugins/Experimental/GeometryCollectionPlugin/Source/GeometryCollectionNodes/Public/Dataflow/GeometryCollectionSamplingNodes.h'],'Public C++ geometry; beta GeometryCollection Dataflow wrappers','Mesh surface','Medial sphere graph/tree',False,False,False,True,'Supporting geometry only; Phase4A failures preserved',['ComputeSkeleton','FSkeletonViaSampling','MedialSkeleton'])
add('SkeletonModifier / static conversion',['Plugins/Runtime/MeshModelingToolset/Source/SkeletalMeshModifiers/Public/SkeletonModifier.h','Plugins/Animation/SkeletalMeshModelingTools/Source/SkeletalMeshModelingTools/Private/SkeletalMeshModelingToolsMeshConverter.cpp'],'Public C++/Blueprint/Python SkeletonModifier subset; private Editor converter','Explicit joints or existing skeleton/root placement','Authored hierarchy and mesh',False,False,False,True,'Construction building block',['AddBone','OrientBone','RootBonePlacement','FMeshBoneInfo'])
add('UE automatic skin / skeletal asset creation',['Plugins/Runtime/GeometryScripting/Source/GeometryScriptingCore/Public/GeometryScript/MeshBoneWeightFunctions.h','Plugins/Runtime/GeometryScripting/Source/GeometryScriptingEditor/Public/GeometryScript/CreateNewAssetUtilityFunctions.h'],'Public C++/Blueprint/Python; asset persistence Editor','DynamicMesh and supplied skeleton','Automatic weights and Skeletal Mesh',False,False,False,True,'Proven downstream solution',['ComputeSmoothBoneWeights','GeodesicVoxel','CreateNewSkeletalMesh'])
add('IK Rig automatic characterisation / FBIK templates',['Plugins/Animation/IKRig/Source/IKRigEditor/Private/RigEditor/IKRigAutoCharacterizer.cpp','Plugins/Animation/IKRig/Source/IKRigEditor/Public/RigEditor/IKRigAutoCharacterizer.h','Plugins/Animation/IKRig/Source/IKRigEditor/Public/RigEditor/IKRigController.h'],'Public Editor controller C++/Blueprint/Python; internal characterizer implementation','Existing bone names, parent indices and reference skeleton','Recognised semantic labels, chains and FBIK',False,False,False,True,'Existing-skeleton recognition only',['GetRefSkeleton','ParentIndices','Template','ApplyAuto'])
add('Control Rig / modular rig connectors',['Plugins/Animation/ControlRig/Source/ControlRig/Public/Rigs/ModularRig.h','Plugins/Animation/ControlRig/Source/ControlRig/Public/ModularRig.h'],'Public rig infrastructure C++/Blueprint; editor authoring controllers','Existing rig hierarchy and connector resolutions','Procedural/modular controls',False,False,False,True,'Control templates do not infer mesh anatomy',['Connector','Hierarchy','Resolve'])
add('ML Deformer / NNE',['Plugins/Animation/MLDeformer/MLDeformerFramework/Source/MLDeformerFramework/Public/MLDeformerModel.h','Plugins/Experimental/NNE/Source/NNE/Public/NNE.h'],'Public runtime/model infrastructure; Editor training; reflected model assets','Existing skeletal animation/skinning and trained model','Deformation inference/model execution',False,False,False,'No suitable body-joint model verified','Infrastructure, not semantic fitter',['SkeletalMesh','Bone','Training','Model'])
add('RigMapper',['Plugins/Experimental/Animation/RigMapper/Source/RigMapperEditor/Public/RigMapperEditorSubsystem.h'],'Public Experimental Editor C++/Blueprint/Python; runtime animation node','Existing animation curves/rig mapping definition and skeletal mesh','Mapped animation',False,False,False,True,'Irrelevant to unrigged inference',['ConvertAnimSequence','TargetMesh','Definitions'])
(O/'semantic_api_inventory.json').write_text(json.dumps({'systems':systems,'investigation_complete_for_recorded_scope':True,'negative_conclusion':'No directly reusable supported geometry-to-semantic-Lara joint-only system verified; not a claim of absence from all opaque binaries or future releases','web_sources':['https://dev.epicgames.com/documentation/metahuman/metahuman-creator-from-custom-mesh-tool-in-unreal-engine','https://dev.epicgames.com/documentation/metahuman/metahuman-5-8-release-notes-in-unreal-engine','https://www.unrealengine.com/eula/unreal','https://www.metahuman.com/license']},indent=2),encoding='utf-8')
print([(r['name'],r['installed']) for r in systems])
