import json,hashlib
from pathlib import Path
P=Path(__file__).resolve().parents[2];E=Path('D:/Epic Games/UE_5.8/Engine');O=P/'Documentation/Phase4B'
d=json.loads((O/'semantic_api_inventory.json').read_text())
d['systems']=[s for s in d['systems'] if s['name'] not in ['RigLogic machine-learned joint behaviour','ARKit body tracking / AR pose conversion']]
for name,paths,exposure,inputs,outputs,known,use,terms in [
 ('RigLogic machine-learned joint behaviour',['Plugins/Animation/RigLogic/Source/RigLogicLib/Public/dna/layers/MachineLearnedBehaviorExtReader.h'],'Public DNA C++ interfaces; runtime rig evaluation; no reflected arbitrary-mesh fitter','Existing DNA rig, trained behaviour and input control buffer','Existing rig joint attributes',True,'Rig behaviour rather than anatomical discovery',['getMLJointsInputIndices','getMLJointsOutputIndices']),
 ('ARKit body tracking / AR pose conversion',['Plugins/Runtime/AR/AppleAR/AppleARKit/Source/AppleARKit/Private/AppleARKitConversion.cpp','Source/Runtime/AugmentedReality/Public/ARTypes.h'],'Public reflected AR pose structures; private Apple SDK conversion; supported Apple device runtime','Camera/Apple ARSkeleton3D, not an arbitrary static 3D mesh','Tracked joint poses and skeleton definition',False,'Image/device tracking outside Lara geometry fitting',['ToARPose3D','JointTransforms','FARPose3D']),
]:
    src=[]
    for rel in paths:
        p=E/rel;lines=p.read_text(encoding='utf-8-sig',errors='replace').splitlines();src.append({'path':str(p),'exists':p.exists(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'matches':[{'line':i+1,'excerpt':lines[max(0,i-2):i+4]} for i,l in enumerate(lines) if any(t in l for t in terms)][:20]})
    d['systems'].append({'name':name,'installed':True,'source':src,'plugin_descriptors':{},'public_private_editor_runtime':exposure,'cpp_blueprint_python':exposure,'expected_input':inputs,'produced_output':outputs,'infers_anatomy_from_arbitrary_geometry':False,'requires_known_topology':known,'changes_topology':False,'reuse_without_converting_lara_to_metahuman':'Not applicable to unrigged mesh anatomy','authoring_plugin_callability':'Public boundary technically accessible for its declared input; platform/rig prerequisites apply; not a generic fitting contract','licensing':'Use governed by Engine EULA and any applicable SDK/model terms; no redistribution approval inferred from source availability','classification':use})
d['supplemental_search']='supplemental_search.json; includes vendor text'
d['systems'][0]['authoring_plugin_callability']='ConformToTargetMeshes public exported/reflected Editor subsystem when MetaHumanCharacter plugin loaded and Character editable; native body-state extraction would need public C++/DNA bridge. Current project reflection lacks the subsystem. No project/plugin configuration changed.'
d['technical_legal_limit']='This records exposure and applicable licence sources, not a legal certification or approval to redistribute private model files or Editor modules.'
(O/'semantic_api_inventory.json').write_text(json.dumps(d,indent=2));print('SYSTEMS',len(d['systems']))
(O/'external_inference_inventory.json').write_text(json.dumps({'investigated_after_geometry_failure':True,'installed_or_executed':False,'cloud_dependency':False,'runtime_dependency':False,'candidates':[{'name':'RigNet','primary_repository':'https://github.com/zhan-xu/rignet','paper':'https://arxiv.org/abs/2005.00559','input':'3D mesh, offline learned rig prediction','output':'Skeleton/connectivity and skin weights','semantic_limit':'Variable topology prediction does not guarantee required named humanoid articulations','dependency_class':'Optional local authoring dependency only; model and code licences must be checked before adoption'},{'name':'UniRig','primary_repository':'https://github.com/VAST-AI-Research/UniRig','paper':'https://arxiv.org/abs/2504.12451','input':'3D object mesh, local checkpoint inference','output':'Skeleton hierarchy and skin prediction','semantic_limit':'General object rigging does not certify human anatomical roles','requirements_observed':'Official repository calls for CUDA and at least 8GB GPU memory for inference; environment/checkpoints not installed here','dependency_class':'Optional local authoring dependency only; deployment and model-licence validation outstanding'}]},indent=2))
