"""Source-only preview and canonical export, preserving local UV/polygon arrays."""
import bpy, sys, json, math
import numpy as np
from mathutils import Vector
from pathlib import Path
sys.dont_write_bytecode=True
P=Path(__file__).resolve().parents[2];W=P/'Working/Phase4F';O=P/'Documentation/Phase4F'
for character in ['John','Jane']:
    dst=W/character
    bpy.ops.wm.open_mainfile(filepath=str(dst/'source_working.blend'))
    scene=bpy.context.scene;meshes=[o for o in scene.objects if o.type=='MESH']
    data=np.load(dst/'source_geometry.npz');v=data['vertices'];H=np.ptp(v[:,2]);low=v[:,2].min()
    # Importer axis declarations, sole support and separate toe/shank geometry are explicit evidence.
    evidence=[]
    for sign in [1,-1]:
        boot=v[(sign*v[:,0]>H*.045)&(v[:,2]<low+H*.08)]
        shank=v[(sign*v[:,0]>H*.045)&(v[:,2]>low+H*.20)&(v[:,2]<low+H*.30)]
        anchor=np.median(shank[:,1]);ends=np.quantile(boot[:,1],[.01,.99])
        evidence.append({'side_source_x_sign':sign,'shank_y_cm':float(anchor),'negative_extension_cm':float(anchor-ends[0]),'positive_extension_cm':float(ends[1]-anchor)})
    facing=-1 if sum(e['negative_extension_cm']-e['positive_extension_cm'] for e in evidence)>0 else 1
    heuristic_facing=facing
    if character in ['John','Jane']: facing=-1 # Observed textured face/belt buckle at source -Y; toe-only heuristic contradicted direct images.
    # Source RH up cross forward defines canonical left; canonical determinant must be -1.
    R=np.diag([-facing,facing,1.]);raw=v@R
    shank=v[(v[:,2]>low+H*.20)&(v[:,2]<low+H*.30)]
    origin=np.array([(raw[:,0].max()+raw[:,0].min())/2,np.median(shank[:,1])*facing,low]);scale=180/H
    vn=(raw-origin)*scale
    frame={'rotation_columns_world':R.tolist(),'origin_body_coordinates_cm':origin.tolist(),'source_height_cm':float(H),'target_height_cm':180,'factor':float(scale),
        'ground_plane_points':int((v[:,2]<low+.28).sum()),'paired_shoe_facing_evidence':evidence,'facing_source_y_sign':facing,
        'up_policy':'FBX declared up converted by Blender; DCC +Z checked against paired boot bottom/crown preview. No PCA height-axis assumption for T-pose.',
        'handedness_determinant':float(np.linalg.det(R)),'round_trip_max_cm':float(np.linalg.norm((vn/scale+origin)@R.T-v,axis=1).max())}
    frame['toe_heuristic_facing_source_y_sign']=heuristic_facing
    frame['facing_validation']='A-pose continuation: -Y facing must be verified from source front/back renders BEFORE fitting. No anatomical approval.'
    (O/character/'coordinate_frame.json').write_text(json.dumps(frame,indent=2))
    np.savez(dst/'normalised_geometry.npz',vertices=vn,triangles=data['triangles'],uv_loops=data['uv_loops'],weld_component=data['weld_component'])
    # Preview in original DCC space; no anatomy approval is generated by these renders.
    scene.render.engine='CYCLES';scene.cycles.samples=12;scene.cycles.device='CPU'
    scene.render.resolution_x=650;scene.render.resolution_y=850;scene.render.resolution_percentage=100
    if scene.world is None: scene.world=bpy.data.worlds.new('Phase4F_SourceWorld')
    scene.world.color=(.65,.65,.65)
    world=scene.world;world.use_nodes=True;world.node_tree.nodes['Background'].inputs['Color'].default_value=(.75,.75,.75,1)
    world.node_tree.nodes['Background'].inputs['Strength'].default_value=.8
    camera=bpy.data.objects.new('Phase4F_SourceCamera',bpy.data.cameras.new('Phase4F_SourceCamera'));scene.collection.objects.link(camera);scene.camera=camera
    camera.data.type='ORTHO'
    centre=Vector((0,0,(low+H*.5)/100))
    light=bpy.data.objects.new('Phase4F_Key',bpy.data.lights.new('Phase4F_Key','AREA'));scene.collection.objects.link(light)
    light.data.energy=350;light.data.shape='DISK';light.data.size=4;light.location=(2,-3,4)
    light.rotation_euler=(centre-light.location).to_track_quat('-Z','Y').to_euler()
    views=[('front',(0,facing*3,centre.z),centre,1.35),('side',(3,0,centre.z),centre,1.35),('back',(0,-facing*3,centre.z),centre,1.35)]
    if character!='Lara':
        hand=v[(v[:,0]>np.quantile(v[:,0],.94))];hc=Vector(np.mean(hand,axis=0)/100)
        views.append(('hand',(hc.x, hc.y+facing*1, hc.z+.18),hc,.24))
    for name,pos,target,ortho in views:
        camera.location=pos;camera.rotation_euler=(target-camera.location).to_track_quat('-Z','Y').to_euler();camera.data.ortho_scale=ortho
        scene.render.filepath=str(O/character/f'source_{name}.png');bpy.ops.render.render(write_still=True)
    # Export physical cm coordinates to UE: DCC RH [canonical X,-canonical Y,Z].
    for ob in meshes:
        source=np.array([list(ob.matrix_world@p.co) for p in ob.data.vertices])*100
        canonical=(source@R-origin)*scale
        ob.matrix_world.identity()
        for vert,p in zip(ob.data.vertices,canonical):vert.co=(p[0],-p[1],p[2])
    scene.unit_settings.system='METRIC';scene.unit_settings.scale_length=.01
    bpy.ops.object.select_all(action='DESELECT')
    for ob in meshes:ob.select_set(True)
    bpy.context.view_layer.objects.active=meshes[0]
    bpy.ops.export_scene.fbx(filepath=str(dst/'Target180.fbx'),use_selection=True,object_types={'MESH'},global_scale=1,apply_unit_scale=True,apply_scale_options='FBX_SCALE_ALL',axis_forward='-Y',axis_up='Z',bake_anim=False,path_mode='ABSOLUTE',mesh_smooth_type='FACE')
    print('PREPARED',character,frame,flush=True)
