"""Independent acceptance and preservation classification from native evidence."""
import json,hashlib,collections,subprocess
from pathlib import Path
R=Path(r'E:/Repo/UE/Projects/MetaHumanTo3DCharacter');W=Path(__file__).parent;O=R/'Documentation/FinalAcceptance/FemaleBodyRigged';read=lambda n:json.loads((O/n).read_text());sha=lambda p:hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
M=read('animation_library_manifest.json');F=read('fresh_validation.json');N=read('native_library.json');I=read('native_verification.json');A=read('R2/authoring_result.json');P=read('preservation_audit.json');V=read('review_build.json');base=read('baseline.json');source=json.loads((R/'Documentation/R4/AegisNX7/animation_library_manifest.json').read_text());checks={}
checks['confirmed_archive_matches_imported_fbx']=read('input_selection.json')['status']=='PASS' and read('input_selection.json')['archive_fbx']['sha256']==sha(Path(read('input_selection.json')['fbx']))
checks['unchanged_R2_execution']=read('R2/author_execution_identity.json')['algorithm_unchanged']
checks['input_unit_semantics_native_processor']=A['status']=='PASS' and all(s['status']=='PASS' for s in A['stages']) and read('R2/semantic_mapping.json')['semantic_binding_count']==23 and read('R2/retarget_setup.json')['processor_initialised']
checks['canonicalisation_preserves_source']=all(read('R2/canonicalisation.json')['invariants'].values())
checks['same_authoritative_89_default_sources']={r['source_path'] for r in M['entries'] if r['classification']=='BAKE_DEFAULT'}=={r['source_path'] for r in source['entries'] if r['classification']=='BAKE_DEFAULT'} and read('source_inventory.json')['accepted_manifest_sha256']==sha(R/'Documentation/R4/AegisNX7/animation_library_manifest.json')
checks['R4_executable_and_generic_core_unchanged']=all(sha(W/n)==sha(R/'Working/R4/AegisNX7'/n) for n in ['bake.py','validate_saved.py','native_library.py']) and sha(R/'Working/R4/animation_library.py')==base['protected']['Working/R4/animation_library.py']['sha256']
rows=[r for r in M['entries'] if r.get('bake_result')=='PASS'];checks['all_89_default_bakes']=M['status']=='PASS' and M['totals']['default']==M['totals']['attempted']==M['totals']['succeeded']==89 and M['totals']['failed']==0
checks['unique_destination_paths']=len({r['destination_path'] for r in rows})==89
checks['fresh_library_reload']=F['status']=='PASS' and F['total']==89 and {r['path'] for r in F['animations']}=={r['destination_path'] for r in rows}
checks['destination_asset_hashes_stable']=all(sha((R/'Content'/r['path'].split('.')[0].removeprefix('/Game/')).with_suffix('.uasset'))==r['sha256'] for r in F['animations'])
checks['source_classification_root_policy_metadata_retained']=all(all(r['metadata_comparison'].values()) and r['root_flags']==r['destination_metadata']['root_flags'] and r['category']==next(s['category'] for s in source['entries'] if s['source_path']==r['source_path']) for r in rows)
checks['source_bound_root_certificates']=all(r['validation']['source_bound_root_deltas']==f['validation']['source_bound_root_deltas'] and f['validation']['status']=='PASS' for r,f in zip(rows,F['animations']))
checks['native_representative_playback']=N['status']=='PASS' and len(N['phases'])==8 and all(r['status']=='PASS' for r in N['phases'])
checks['native_all_controls']=I['status']=='PASS' and len(I['phases'])==9 and all(r['status']=='PASS' for r in I['phases'])
j=I['phases'][-1]['air_observations'];checks['jump_fall_land_ground_return']=any(r['jump_start'] and r['airborne'] and r['vertical_velocity']>0 for r in j) and any(r['airborne'] and not r['jump_start'] and r['vertical_velocity']<0 for r in j) and any(r['landing'] for r in j) and not j[-1]['landing'] and not j[-1]['airborne']
closure=F['runtime_dependency_closure'];checks['destination_runtime_independent']=closure['certificate']['status']=='PASS' and not closure['authoring_packages'] and not F['bridge_loaded'] and not any('/AegisNX7/' in p or '/Mannequins/' in p or '/Phase4F/Jane/' in p or '/Phase4F/John/' in p for p in closure['packages'])
original_inventory=json.loads((R/'Documentation/FinalAcceptance/RiggedJane/InputDiscovery/native_input_inventory.json').read_text())
original_mesh=read('input_selection.json')['original_mesh'];original_slots=next(r['material_slots'] for r in original_inventory['skeletal_meshes'] if r['object_path'].split('.')[0]==original_mesh)
checks['original_appearance_bindings_retained']={r['material'].split('.')[0] for r in original_slots if r['material']}==set(closure['certificate']['bound_material_roots'])
generated_prefix='Working/Phase4F/BenchmarkRuns/02_AegisNX7/R3/AuthoringHost/Saved/'
changed_authored=[p for p in P['changed'] if not p.startswith(generated_prefix)];missing_authored=[p for p in P['missing'] if not p.startswith(generated_prefix)]
generated=dict(changed=[p for p in P['changed'] if p.startswith(generated_prefix)],rotated_missing=[p for p in P['missing'] if p.startswith(generated_prefix)],reason='Native UE authoring-host Saved SDK diagnostics and uncontrolled-changelist runtime state; no authored project asset, source or reproducibility evidence')
checks['authored_files_human_evidence_Git_preserved']=not changed_authored and not missing_authored and P['git_preserved']
checks['correct_final_mesh_and_height']=F['skeleton']==A['assets']['skeleton'] and abs(F['height_cm']-read('R2/input_validation.json')['input']['height_cm'])<.001
checks['ready_for_human_review']=I['ready_to_press_Play'] and I['PIE_stopped'] and I['editor_left_open'] and I['review_level_loaded'].split('.')[0]==V['assets']['level']
command=subprocess.check_output(['powershell','-NoProfile','-Command',f"(Get-CimInstance Win32_Process -Filter 'ProcessId={I['pid']}').CommandLine"],text=True);checks['review_editor_running']='Working/FinalAcceptance/RiggedCharacters/FemaleBodyRigged/verify_and_handoff.py' in command.replace('\\','/')
result=dict(status='PASS' if all(checks.values()) else 'FAIL',classification='FINAL_ACCEPTANCE_READY' if all(checks.values()) else 'SUPPORTED_INPUT_BUT_BLOCKED',subject='Female_Body_Rigged.zip, explicitly substituted by the user for rigged Jane',checks=checks,totals=M['totals'],categories=dict(collections.Counter(r['category'] for r in rows)),reference_height_cm=F['height_cm'],jump_rise_cm=max(r['position'][2] for r in j)-min(r['position'][2] for r in j),assets=dict(**A['assets'],**V['assets']),animation_library_root=json.loads((W/'profile.json').read_text())['output_namespace']+'/Animations/LibraryV1',air_sequences={k:V['clips'][k] for k in ['MM_Jump','MM_Fall_Loop','MM_Land']},preservation=dict(status='PASS' if checks['authored_files_human_evidence_Git_preserved'] else 'FAIL',protected_count=P['protected_count'],authored_changes=changed_authored,authored_missing=missing_authored,generated_runtime_changes=generated,runtime_appends=P['runtime_appends'],git_preserved=P['git_preserved'],strict_raw_hash_audit_retained=True),intervention=dict(user_source_correction=1,manual_bone_mapping=0,subject_specific_repairs=0,retarget_tuning=0,landmark_or_human_review_changes=0),editor_pid=I['pid'],human_visual_acceptance='Pending Andre personal review',evidence_hashes={n:sha(O/n) for n in ['animation_library_manifest.json','source_inventory.json','fresh_validation.json','native_library.json','native_verification.json','review_build.json','preservation_audit.json','input_selection.json','R2/authoring_result.json','R2/author_execution_identity.json']})
(O/'final_acceptance.json').write_text(json.dumps(result,indent=2)+'\n');(O/'preservation_classification.json').write_text(json.dumps(result['preservation'],indent=2)+'\n');print(json.dumps({k:result[k] for k in ['status','classification','checks','preservation','editor_pid']},indent=2))
