"""Bake only three common locomotion clips AFTER four-task native live proof passes."""
import unreal,json,sys,traceback,hashlib
from pathlib import Path
sys.dont_write_bytecode=True;R=Path('E:/Repo/UE/Projects/MetaHumanTo3DCharacter');O=R/'Documentation/Phase4F/Benchmark/Runs/01_FemaleBodyRigged/UnitCorrection';B='/Game/MetaHumanTo3DCharacter/Phase4F/BenchmarkRuns/01_FemaleBodyRigged/UnitCorrection';r=dict(status='running',clips=[])
try:
    proof=json.loads((O/'native_live_proof.json').read_text());assert proof['status']=='passed' and len(proof['phases'])==8 and all(x['status']=='PASS' for x in proof['phases']);r['prerequisite_native_proof_sha256']=hashlib.sha256((O/'native_live_proof.json').read_bytes()).hexdigest();d=json.loads((O/'canonicalisation.json').read_text());s=json.loads((O/'live_setup.json').read_text());mesh=unreal.load_asset(d['mesh']);sm=unreal.load_asset('/Game/Characters/Mannequins/Meshes/SKM_Manny_Simple');rt=unreal.load_asset(s['retargeter']);sources={'idle':'/Game/MetaHumanTo3DCharacter/Phase3B/SourceAnimations/InPlace/MM_Idle','walk':'/Game/MetaHumanTo3DCharacter/Phase3B/SourceAnimations/InPlace/MF_Walk_Fwd','run':'/Game/MetaHumanTo3DCharacter/Phase3B/SourceAnimations/InPlace/MM_Run_Fwd'};assert not unreal.EditorAssetLibrary.list_assets(B+'/Animations',True,False)
    inp=unreal.IKRetargetBatchOperationInputs();inp.set_editor_properties(dict(assets_to_retarget=[unreal.EditorAssetLibrary.find_asset_data(x) for x in sources.values()],source_mesh=sm,target_mesh=mesh,ik_retarget_asset=rt,target_path=B+'/Animations',include_referenced_assets=False,overwrite_existing_files=False));baked=unreal.IKRetargetBatchOperation.run_batch_retarget(inp);assert len(baked)==3;byname={x.get_asset().get_name():x.get_asset() for x in baked}
    for role,path in sources.items():
        anim=byname[path.rsplit('/',1)[-1]];assert anim.get_editor_property('skeleton')==mesh.skeleton;assert unreal.EditorAssetLibrary.save_loaded_asset(anim,False);r['clips'].append(dict(role=role,path=anim.get_path_name(),duration_s=anim.get_play_length(),skeleton=mesh.skeleton.get_path_name(),source=path,root_flags={k:str(anim.get_editor_property(k)) for k in ['enable_root_motion','force_root_lock','root_motion_root_lock']}))
    fac=unreal.AnimSequenceFactory();fac.set_editor_property('target_skeleton',mesh.skeleton);refanim=unreal.AssetToolsHelpers.get_asset_tools().create_asset('Reference_Native',B+'/Animations',unreal.AnimSequence,fac);ctl=refanim.get_editor_property('controller');ctl.open_bracket('Own canonical bind reference, no source motion replacement',False);ctl.set_frame_rate(unreal.FrameRate(60,1),False);ctl.set_number_of_frames(unreal.FrameNumber(60),False);ref=mesh.skeleton.get_reference_pose()
    for n in ref.get_bone_names():t=ref.get_bone_pose(n,unreal.AnimPoseSpaces.LOCAL);ctl.add_bone_track(n,False);assert ctl.set_bone_track_keys(n,[t.translation]*61,[t.rotation]*61,[t.scale3d]*61,False)
    ctl.close_bracket(False);refanim.set_preview_skeletal_mesh(mesh);assert unreal.EditorAssetLibrary.save_loaded_asset(refanim,False);r['clips'].insert(0,dict(role='neutral',path=refanim.get_path_name(),duration_s=refanim.get_play_length(),skeleton=mesh.skeleton.get_path_name(),source=None,purpose='Own imported reference only'))
    r['status']='passed'
except Exception:r.update(status='failed',error=traceback.format_exc())
(O/'native_bake.json').write_text(json.dumps(r,indent=2));print('UNIT_NATIVE_BAKE',r['status'],r.get('error',''))
