"""Fresh MAIN-project native SingleNode PIE playback: no source/retarget/native-bridge evaluation."""
import unreal,json,sys,time,math,traceback
from pathlib import Path
sys.dont_write_bytecode=True;R=Path('E:/Repo/UE/Projects/MetaHumanTo3DCharacter');O=R/'Documentation/Phase4F/Benchmark/Runs/01_FemaleBodyRigged/UnitCorrection';B='/Game/MetaHumanTo3DCharacter/Phase4F/BenchmarkRuns/01_FemaleBodyRigged/UnitCorrection';d=json.loads((O/'canonicalisation.json').read_text());b=json.loads((O/'native_bake.json').read_text());assert b['status']=='passed';VIS=O/'NativeBaked';VIS.mkdir(exist_ok=True);r=dict(status='running',fresh_process=True,native_game_world=True,source_actor_count=0,live_retarget_node_count=0,native_bridge_loaded=hasattr(unreal,'RiggedUnitBridgeLibrary'),phases=[])
unreal.EditorPythonScripting.set_keep_python_script_alive(True);assert not r['native_bridge_loaded'];assert unreal.EditorLevelLibrary.new_level(B+'/Playback/L_BakedProof');E=unreal.get_editor_subsystem(unreal.EditorActorSubsystem);U=unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem);actor=E.spawn_actor_from_class(unreal.SkeletalMeshActor,unreal.Vector());c=actor.skeletal_mesh_component;mesh=unreal.load_asset(d['mesh']);c.set_skeletal_mesh_asset(mesh);c.set_forced_lod(1);c.set_update_animation_in_editor(True);c.play_animation(unreal.load_asset(b['clips'][0]['path']),True)
floor=E.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(0,0,-5));floor.static_mesh_component.set_static_mesh(unreal.load_asset('/Engine/BasicShapes/Cube'));floor.set_actor_scale3d(unreal.Vector(30,30,.1));E.spawn_actor_from_class(unreal.DirectionalLight,unreal.Vector(0,0,250),unreal.Rotator(pitch=-45,yaw=-45,roll=0));E.spawn_actor_from_class(unreal.SkyLight,unreal.Vector(0,0,250));assert unreal.EditorLevelLibrary.save_current_level();h=d['bounds_height_cm'];location=unreal.Vector(0,1.6*h,h*.55);U.set_level_viewport_camera_info(location,unreal.MathLibrary.find_look_at_rotation(location,unreal.Vector(0,0,h*.5)));unreal.EditorLevelLibrary.editor_set_game_view(True);unreal.AutomationLibrary.set_editor_viewport_view_mode(unreal.ViewModeIndex.VMI_UNLIT)
reg=unreal.AssetRegistryHelpers.get_asset_registry();reg.search_all_assets(True);opts=unreal.AssetRegistryDependencyOptions(include_soft_package_references=True,include_hard_package_references=True,include_searchable_names=True,include_soft_management_references=True,include_hard_management_references=True);seeds=[d['mesh'].split('.')[0],d['skeleton'].split('.')[0]]+[x['path'].split('.')[0] for x in b['clips']];seen=set();todo=seeds[:];edges={}
while todo:
    p=todo.pop()
    if p in seen:continue
    seen.add(p);dep=[str(x) for x in reg.get_dependencies(p,opts)];edges[p]=dep;todo.extend(x for x in dep if x not in seen)
r['dependency_closure']=dict(packages=sorted(seen),edges=edges,foreign_game_packages=[p for p in seen if p.startswith('/Game/') and not p.startswith(B+'/')],authoring_packages=[p for p in seen if '/Retarget/' in p],bridge_references=[p for p in seen if 'RiggedUnitBridge' in p]);assert not any(r['dependency_closure'][k] for k in ['foreign_game_packages','authoring_packages','bridge_references'])
unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).editor_play_simulate();ready=False;phases=[(x,speed) for speed in [1,.25] for x in b['clips']];stage=0;start=None;last=0;rows=[];shots=set();geometries=[]
def v(x):return [x.x,x.y,x.z]
def tick(delta):
    global ready,actor,c,stage,start,last,rows,shots,geometries
    try:
        if not ready:
            world=U.get_game_world()
            if not world:return
            actors=unreal.GameplayStatics.get_all_actors_of_class(world,unreal.SkeletalMeshActor);assert len(actors)==1;actor=actors[0];c=actor.skeletal_mesh_component;ready=True
        row,speed=phases[stage];now=time.perf_counter();cycles=2 if row['role'] in ['walk','run'] else 1;total=row['duration_s']*cycles/speed
        if start is None:
            anim=unreal.load_asset(row['path']);assert anim.get_editor_property('skeleton')==mesh.skeleton;c.play_animation(anim,True);c.set_play_rate(speed);start=now;last=0;rows=[];shots=set();geometries=[];return
        elapsed=now-start
        if elapsed>.15 and elapsed-last>=1/60:
            last=elapsed;bones={n:v(c.get_socket_location(n)) for n in d['bones']};root=c.get_socket_transform('root',unreal.RelativeTransformSpace.RTS_COMPONENT);carrier=next(n for n,bn in d['bones'].items() if bn['parent'] is None);lengths={n:math.dist(bones[n],bones[bn['parent']]) for n,bn in d['bones'].items() if bn['parent'] and bn['parent']!=carrier};rows.append(dict(elapsed_s=elapsed,position_s=c.get_position(),bones=bones,root_scale=v(root.scale3d),component_scale=v(c.get_world_transform().scale3d),actor_location=v(actor.get_actor_location()),segment_lengths_cm=lengths))
        for fraction in [.25,.5,.75]:
            if elapsed>=fraction*total and fraction not in shots:
                path=VIS/(row['role']+'_'+str(speed)+'_'+str(fraction)+'.png');assert unreal.AutomationLibrary.take_high_res_screenshot(1920,1080,str(path));shots.add(fraction)
                dm=unreal.DynamicMesh();opt=unreal.GeometryScriptCopyMeshFromComponentOptions();opt.set_editor_property('requested_lod',unreal.GeometryScriptMeshReadLOD(lod_type=unreal.GeometryScriptLODType.SOURCE_MODEL,lod_index=0));_,_,ok=unreal.GeometryScript_SceneUtils.copy_mesh_from_component(c,dm,opt,True);assert ok==unreal.GeometryScriptOutcomePins.SUCCESS;Q=unreal.GeometryScript_MeshQueries;pts=[v(Q.get_vertex_position(dm,i)[0]) for i in range(Q.get_num_vertex_i_ds(dm))];mins=[min(p[j] for p in pts) for j in range(3)];maxs=[max(p[j] for p in pts) for j in range(3)];geometries.append(dict(fraction=fraction,position_s=c.get_position(),bounds=[mins,maxs],finite=all(math.isfinite(x) for p in pts for x in p),vertex_count=len(pts),triangle_count=Q.get_num_triangle_i_ds(dm)))
        if elapsed>=total+.2:
            assert rows;max_limb_error=max(abs(length-math.dist(d['bones'][n]['component']['translation'],d['bones'][d['bones'][n]['parent']]['component']['translation'])) for z in rows for n,length in z['segment_lengths_cm'].items());rooterr=max(abs(x-1) for z in rows for x in z['root_scale']);pelvis=[min(z['bones']['pelvis'][2] for z in rows),max(z['bones']['pelvis'][2] for z in rows)];motions={n:max(math.dist(z['bones'][n],rows[0]['bones'][n]) for z in rows) for n in ['hand_l','hand_r','foot_l','foot_r']};advanced=row['role']=='neutral' or max(z['position_s'] for z in rows)-min(z['position_s'] for z in rows)>.1;moved=row['role']=='neutral' or max(motions.values())>.001;passed=rooterr<1e-4 and max_limb_error<.01 and advanced and moved and 20<pelvis[0]<pelvis[1]+.01<100 and all(g['finite'] for g in geometries)
            r['phases'].append(dict(role=row['role'],speed=speed,status='PASS' if passed else 'FAIL',sample_count=len(rows),pelvis_z_range_cm=pelvis,max_limb_length_error_cm=max_limb_error,max_root_scale_error=rooterr,motion_excursion_cm=motions,geometry_samples=geometries,samples=rows));(O/'native_baked_proof.json').write_text(json.dumps(r));stage+=1;start=None
            if stage==len(phases):r['status']='passed' if all(x['status']=='PASS' for x in r['phases']) else 'failed';(O/'native_baked_proof.json').write_text(json.dumps(r));unreal.unregister_slate_post_tick_callback(handle);unreal.SystemLibrary.quit_editor()
    except Exception:r.update(status='failed',error=traceback.format_exc());(O/'native_baked_proof.json').write_text(json.dumps(r));unreal.unregister_slate_post_tick_callback(handle);unreal.SystemLibrary.quit_editor()
handle=unreal.register_slate_post_tick_callback(tick)
