"""Native source-free Sequencer/PIE movie in clean project; no live retargeter or source assets."""
import unreal,json,sys,traceback
from pathlib import Path
sys.dont_write_bytecode=True;R=Path('E:/Repo/UE/Projects/MetaHumanTo3DCharacter');O=R/'Documentation/Phase4F/Benchmark/Runs/01_FemaleBodyRigged';folder=O/'NativeSourceFreeFrames';folder.mkdir(exist_ok=True);r=dict(status='running',native=True,source_free=True,quality_approval_inferred=False)
def done(success):
    r.update(status='passed' if success else 'failed',native_render_callback_success=success);(O/'source_free_movie_capture.json').write_text(json.dumps(r,indent=2));unreal.SystemLibrary.quit_editor()
try:
    assert 'CleanProject' in unreal.Paths.get_project_file_path();unreal.EditorPythonScripting.set_keep_python_script_alive(True);e=json.loads((O/'source_free_sequence.json').read_text());assert e['status']=='passed';assert unreal.EditorLevelLibrary.load_level(e['map']);seq=unreal.load_asset(e['sequence'])
    capture=unreal.AutomatedLevelSequenceCapture();settings=capture.get_editor_property('settings');settings.set_editor_properties(dict(output_directory=unreal.DirectoryPath(str(folder)),output_format='destination.{frame}',resolution=unreal.CaptureResolution(1920,1080),use_custom_frame_rate=True,custom_frame_rate=unreal.FrameRate(30,1),overwrite_existing=False,use_relative_frame_numbers=True));capture.set_editor_property('settings',settings)
    capture.set_editor_properties(dict(level_sequence_asset=unreal.SoftObjectPath(seq.get_path_name()),use_custom_start_frame=True,custom_start_frame=unreal.FrameNumber(0),use_custom_end_frame=True,custom_end_frame=unreal.FrameNumber(seq.get_playback_end()),warm_up_frame_count=30,delay_before_warm_up=1,use_separate_process=True,additional_command_line_arguments='-RenderOffscreen -ForceRes -NoAnalytics -NoAutoSave -nosound -ExecCmds="viewmode unlit,r.DepthOfFieldQuality 0,r.MotionBlurQuality 0,r.ScreenPercentage 100,DisableAllScreenMessages"'))
    jpg=next(getattr(unreal,n) for n in dir(unreal) if n.startswith('ImageSequenceProtocol') and n.endswith('JPG'));capture.set_image_capture_protocol_type(jpg);r.update(sequence=seq.get_path_name(),map=e['map'],frame_count=e['frame_count'],frame_rate=[30,1],resolution=[1920,1080],normal_and_quarter_native_sequence_rates=True,source_packages_unavailable=True,diagnostic_camera=e['camera'],root_motion_world_test=False);(O/'source_free_movie_capture.json').write_text(json.dumps(r,indent=2));callback=unreal.OnRenderMovieStopped();callback.bind_callable(done);assert unreal.SequencerTools.render_movie(capture,callback)
except Exception:r.update(status='failed',error=traceback.format_exc());(O/'source_free_movie_capture.json').write_text(json.dumps(r,indent=2));unreal.SystemLibrary.quit_editor()
